name: Build st in Debian Stable Container

on:
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  
   

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2


    - name:  build 
      run: |
       sudo apt update -y
       sudo apt install -y  zip git gcc meson make ca-certificates binutils libasound2-dev libgtk-layer-shell-dev libgtk-3-dev libjson-c-dev  --no-install-recommends
       bash build.sh
       upload=$(realpath sfwbar/output.zip)
       echo "FILE1=${upload}" >> $GITHUB_ENV 

    - name: Create GitHub Release and Upload ZIP
      uses: softprops/action-gh-release@v2
      with:
          tag_name: 1.0.0
          files: |
              ${{ env.FILE1 }}
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}       
       
       
      
