name: Build sfwbar in ubuntu latest Container

on:
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name:  build 
      run: |
       sudo apt update -y
       sudo apt install -y  zip git gcc meson make ca-certificates binutils libasound2-dev libgtk-layer-shell-dev libgtk-3-dev libjson-c-dev  --no-install-recommends
       bash build.sh
       echo "FILE1=$(realpath sfwbar/output.zip)" >> $GITHUB_ENV 
       echo "FILE2=$(realpath sfwbar//build/sfwbar)" >> $GITHUB_ENV 
       echo "FILE3=$(realpath sfwbar/build/libsfwbar.so)" >> $GITHUB_ENV 

    - name: Create GitHub Release and Upload ZIP
      uses: softprops/action-gh-release@v2
      with:
          tag_name: latest
          files: |
              ${{ env.FILE1 }}
               ${{ env.FILE2 }}
                ${{ env.FILE3 }}
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}       
       
       
      
